LearningDjango/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls'))
]

LearningDjango/mysite/polls/urls.py
from django.urls import path
from . import views

app_name='polls'
urlpatterns = [
    # path('', views.index, name='index'),
    # path('<int:question_id>/',views.detail,name="detail"),
    # path('<int:question_id>/results/',views.results,name='results'),
    path('',views.IndexView.as_view(),name='index'),
    path('<int:pk>/',views.DetailView.as_view(),name='detail'),
    path('<int:pk>/results',views.ResultsView.as_view(),name='results'),
    path('<int:question_id>/vote/',views.vote,name='vote')
]

LearningDjango/mysite/polls/models.py
from django.db import models
from datetime import datetime
# Create your models here.
class Questions(models.Model):
    question_text = models.CharField('Actual Question', max_length=200)
    pub_date = models.DateTimeField('date published')

    # def __repr__(self):
    #     return f"Questions(question_text='{self.question_text}',pub_date='{self.pub_date}')"

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Questions, on_delete=models.CASCADE)
    choice = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice

LearningDjango/mysite/polls/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.http import HttpResponse, HttpResponseRedirect
from .models import Questions, Choice
from django.views import generic

class IndexView(generic.ListView):
    template_name='polls/index.html'
    context_object_name='latest_question_list'

    def get_queryset(self):
        return Questions.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model=Questions
    template_name='polls/detail.html'
    context_object_name='question'

class ResultsView(generic.DetailView):
    model=Questions
    template_name='polls/results.html'
    context_object_name='question'
# Create your views here.
# def index(request):
#     latest_question_list=Questions.objects.order_by('-pub_date')
#     output=','.join([q.question_text for q in latest_question_list])
#     return render(request,'polls/index.html',{'latest_question_list':latest_question_list})
#
# def detail(request, question_id):
#     q=get_object_or_404(Questions,pk=question_id)
#     return render(request,'polls/detail.html',{'question':q})
#
# def results(request, question_id):
#     question = get_object_or_404(Questions,pk=question_id)
#     return render(request, 'polls/results.html',{'question':question})

def vote(request,question_id):
    question = get_object_or_404(Questions,pk=question_id)
    try:
        selected_choice=question.choice_set.get(pk=request.POST['choice'])
    except(KeyError,Choice.DoesNotExist):
        return render(request,'polls/detail.html',{'question':question,'error_message':'Please select a choice first.'})
    else:
        selected_choice.votes+=1
        selected_choice.save()
        return HttpResponseRedirect(reverse("polls:results",args=(question_id,)))

LearningDjango/mysite/templates/base.html
{% load static %}
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
    <meta charset="UTF-8">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'css/all.css' %}">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <!-- Custom -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- LightBox -->
    <link rel="stylesheet" href="{% static 'css/lightbox.min.css' %}">
    <title>Learning Django</title>
</head>
<body>
{% block content %}
{% endblock %}
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/lightbox.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
</body>
</html>

LearningDjango/mysite/templates/polls/detail.html
{% extends 'base.html' %}
{% block content %}

<h2>{{question.question_text}}</h2>

{% if error_message %}
<p><string>{{error_message}}</string></p>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="POST">
    {% csrf_token %}
    {% for ch in question.choice_set.all %}
        <input type="radio" name="choice" id="ch{{ forloop.counter }}" value="{{ch.id}}">
        <label for="ch{{ forloop.counter }}">{{ch.choice}}</label><br>
    {% endfor %}
    <br>
    <input type="submit" value="Vote">
</form>
{% endblock %}

LearningDjango/mysite/templates/polls/index.html
{% extends 'base.html' %}
{% block content %}
{% if latest_question_list %}
<ul>
    {% for q in latest_question_list %}
    <li><a href="{% url 'polls:detail' q.id %}">{{q.question_text}}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %}
{% endblock %}

LearningDjango/mysite/templates/polls/results.html
{% extends 'base.html' %}
{% block content %}

<h2>{{question.question_text}}</h2>

<ul>
    {% for ch in question.choice_set.all %}
        <li>{{ch.choice}} -- {{ch.votes}} vote{{ch.votes|pluralize}}</li>
    {% endfor %}
</ul>
<a href="{% url 'polls:detail' question.id %}">Vote Again?</a>

{% endblock %}